[build]
command = "[ -x \"$(command -v trunk)\" ] || cargo install trunk && trunk build --release --public-url /wordle-rs/"
publish = "dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/*"
to = "https://rpeabs.net/wordle-rs/:splat"
status = 301
force = true
